### ISSUE TITLE
About the api

### ISSUE THREAD

**Issue by binarf** [saitenasuk/koishi-plugin-kimi-api#1]
Excuse me, how did you get this api? I tried to enter the sample api directly, but it will return.An error occurred: fetch failed.

**Comment by saitenasuk** [comment]
> 请问一下，你是怎么获取这个api的？我尝试直接进入示例api，但是会返回“发生错误：fetch failed”。

如果你需要使用大模型，需要自行部署[kimi-free-api](https://github.com/your-repo/kimi-free-api)。如何要解析抖音链接或者tiktok-url，需要部署[Douyin_TikTok_Download_API](https://github.com/your-repo/Douyin_TikTok_Download_API)

**Comment by saitenasuk** [comment]
> 请问一下，你是怎么获取这个api的？我尝试直接进入示例api，但是会返回“发生错误：fetch failed”。

如果你需要使用大模型，需要自行部署[kimi-free-api](https://github.com/your-repo/kimi-free-api)。如何要解析抖音链接或者tiktok-url，需要部署[Douyin_TikTok_Download_API](https://github.com/your-repo/Douyin_TikTok_Download_API)
